const Report = require('../models/Report');
const reportService = require('../services/reportService');
const auditService = require('../services/auditService');
const notificationService = require('../services/notificationService');
const { sendSuccess, sendError } = require('../utils/apiResponse');

// 1. Get all reports with optional filtering
exports.getReports = async (req, res, next) => {
  try {
    const query = req.user.role === 'admin' ? {} : { generatedBy: req.user._id };
    if (req.query.status) query.status = req.query.status;
    if (req.query.type) query.type = req.query.type;

    const reports = await Report.find(query)
      .populate('generatedBy', 'username')
      .populate('reviewerId', 'username')
      .populate('approvedBy', 'username')
      .sort({ createdAt: -1 });

    return sendSuccess(res, reports, 'Reports retrieved successfully');
  } catch (error) {
    next(error);
  }
};

// 2. Generate a new report
exports.generateReport = async (req, res, next) => {
  try {
    const { data, type } = req.body;
    if (!type) {
      return sendError(res, 'Report type is required', 'VALIDATION_ERROR', 400);
    }
    const reqContext = { userId: req.user._id, isComplex: true };
    const report = await reportService.generateReport(data || {}, type, req.user._id, reqContext);

    // Notify admins about new report
    try {
      notificationService.notifyAdmins(
        `New ${type} report generated by ${req.user.username}: "${report.title}"`,
        'info', 'report', report._id
      );
    } catch (notifErr) {
      console.warn('Failed to dispatch notification:', notifErr.message);
    }

    return sendSuccess(res, report, 'Report generated successfully', 201);
  } catch (error) {
    next(error);
  }
};

// 3. Get single report by ID
exports.getReportById = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id)
      .populate('generatedBy', 'username')
      .populate('reviewerId', 'username')
      .populate('approvedBy', 'username');

    if (!report) {
      return sendError(res, 'Report not found', 'NOT_FOUND', 404);
    }

    const isCreator = report.generatedBy?._id?.toString() === req.user._id.toString() ||
                      report.generatedBy?.toString() === req.user._id.toString();

    if (req.user.role !== 'admin' && req.user.role !== 'reviewer' && !isCreator) {
      return sendError(res, 'Not authorized to view this report', 'FORBIDDEN', 403);
    }

    return sendSuccess(res, report, 'Report retrieved successfully');
  } catch (error) {
    next(error);
  }
};

// 4. Update report content / title / metadata
exports.updateReport = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) {
      return sendError(res, 'Report not found', 'NOT_FOUND', 404);
    }

    const isCreator = report.generatedBy?._id?.toString() === req.user._id.toString() ||
                      report.generatedBy?.toString() === req.user._id.toString();

    if (req.user.role !== 'admin' && !isCreator) {
      return sendError(res, 'Not authorized to update this report', 'FORBIDDEN', 403);
    }

    const { title, content, markdown, language } = req.body;

    // Snapshot version before updating
    report.previousVersions.push({
      content: report.content,
      version: report.version || 1,
      date: new Date()
    });
    report.version = (report.version || 1) + 1;

    if (title && typeof title === 'string' && title.trim()) {
      report.title = title.trim();
    }

    if (markdown !== undefined) {
      report.content = report.content || {};
      report.content.markdown = markdown;
    } else if (content !== undefined) {
      if (typeof content === 'string') {
        report.content = report.content || {};
        report.content.markdown = content;
      } else if (typeof content === 'object') {
        report.content = {
          ...report.content,
          ...content
        };
      }
    }

    if (language) {
      report.language = language;
    }

    // If report was rejected, updating it moves it back to draft
    if (report.status === 'rejected') {
      report.status = 'draft';
    }

    await report.save();

    try {
      await auditService.logAudit({
        user: req.user._id,
        action: 'UPDATE_REPORT',
        resource: 'Report',
        resourceId: report._id,
        details: { newVersion: report.version, title: report.title }
      });
    } catch (auditErr) {
      console.warn('Audit logging failed:', auditErr.message);
    }

    return sendSuccess(res, report, 'Report updated successfully');
  } catch (error) {
    next(error);
  }
};

// 5. Delete report
exports.deleteReport = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) {
      return sendError(res, 'Report not found', 'NOT_FOUND', 404);
    }

    const isCreator = report.generatedBy?._id?.toString() === req.user._id.toString() ||
                      report.generatedBy?.toString() === req.user._id.toString();

    if (req.user.role !== 'admin' && !isCreator) {
      return sendError(res, 'Not authorized to delete this report', 'FORBIDDEN', 403);
    }

    await Report.findByIdAndDelete(req.params.id);

    try {
      await auditService.logAudit({
        user: req.user._id,
        action: 'DELETE_REPORT',
        resource: 'Report',
        resourceId: req.params.id,
        details: { title: report.title, type: report.type }
      });
    } catch (auditErr) {
      console.warn('Audit logging failed:', auditErr.message);
    }

    return sendSuccess(res, { id: req.params.id }, 'Report deleted successfully');
  } catch (error) {
    next(error);
  }
};

// 6. Submit report for review
exports.submitForReview = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) {
      return sendError(res, 'Report not found', 'NOT_FOUND', 404);
    }

    if (report.status !== 'draft' && report.status !== 'rejected') {
      return sendError(res, `Cannot submit a report with status "${report.status}"`, 'INVALID_STATUS', 400);
    }

    const { reviewerId } = req.body;
    report.status = 'review';
    if (reviewerId) report.reviewerId = reviewerId;
    await report.save();

    try {
      await auditService.logAudit({
        user: req.user._id,
        action: 'SUBMIT_FOR_REVIEW',
        resource: 'Report',
        resourceId: report._id,
        details: { reviewerId, previousStatus: report.status }
      });
    } catch (auditErr) {
      console.warn('Audit logging failed:', auditErr.message);
    }

    try {
      if (reviewerId) {
        notificationService.notify(
          reviewerId,
          `Report "${report.title}" has been submitted for your review.`,
          'action', 'review', report._id
        );
      } else {
        notificationService.notifyAdmins(
          `Report "${report.title}" is awaiting review.`,
          'action', 'review', report._id
        );
      }
    } catch (notifErr) {
      console.warn('Notification failed:', notifErr.message);
    }

    return sendSuccess(res, report, 'Report submitted for review successfully');
  } catch (error) {
    next(error);
  }
};

// 7. Get pending reviews
exports.getPendingReviews = async (req, res, next) => {
  try {
    const pendingReports = await Report.find({ status: 'review' })
      .populate('generatedBy', 'username')
      .populate('reviewerId', 'username')
      .sort({ updatedAt: -1 });

    return sendSuccess(res, pendingReports, 'Pending reviews retrieved successfully');
  } catch (error) {
    next(error);
  }
};

// 8. Get review by ID
exports.getReviewById = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id)
      .populate('generatedBy', 'username')
      .populate('reviewerId', 'username')
      .populate('approvedBy', 'username');

    if (!report) {
      return sendError(res, 'Report not found', 'NOT_FOUND', 404);
    }

    return sendSuccess(res, report, 'Review details retrieved successfully');
  } catch (error) {
    next(error);
  }
};

// 9. Approve report (ADMIN ONLY)
exports.approveReport = async (req, res, next) => {
  try {
    // Admin approval must remain strictly admin-only
    if (req.user.role !== 'admin') {
      return sendError(res, 'Admin privileges required to approve reports', 'FORBIDDEN', 403);
    }

    const report = await Report.findById(req.params.id);
    if (!report) {
      return sendError(res, 'Report not found', 'NOT_FOUND', 404);
    }

    if (report.status !== 'review') {
      return sendError(res, 'Only reports in "review" status can be approved', 'INVALID_STATUS', 400);
    }

    report.status = 'approved';
    report.approvedBy = req.user._id;
    report.approvedAt = new Date();
    report.reviewerComments = req.body.comments || req.body.reason || '';
    report.reviewedAt = new Date();
    await report.save();

    try {
      await auditService.logAudit({
        user: req.user._id,
        action: 'APPROVE_REPORT',
        resource: 'Report',
        resourceId: report._id,
        details: { comments: report.reviewerComments }
      });
    } catch (auditErr) {
      console.warn('Audit logging failed:', auditErr.message);
    }

    try {
      if (report.generatedBy) {
        notificationService.notify(
          report.generatedBy,
          `Your report "${report.title}" has been approved.`,
          'success', 'approval', report._id
        );
      }
    } catch (notifErr) {
      console.warn('Notification failed:', notifErr.message);
    }

    return sendSuccess(res, report, 'Report approved successfully');
  } catch (error) {
    next(error);
  }
};

// 10. Reject report (Admin/Reviewer)
exports.rejectReport = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) {
      return sendError(res, 'Report not found', 'NOT_FOUND', 404);
    }

    if (report.status !== 'review') {
      return sendError(res, 'Only reports in "review" status can be rejected', 'INVALID_STATUS', 400);
    }

    // Preservation of rejection reason
    const reason = req.body.comments || req.body.reason;
    if (!reason || typeof reason !== 'string' || !reason.trim()) {
      return sendError(res, 'A non-empty rejection reason or comment is required', 'VALIDATION_ERROR', 400);
    }

    // Save current version before rejecting
    report.previousVersions.push({
      content: report.content,
      version: report.version || 1,
      date: new Date()
    });

    report.status = 'rejected';
    report.reviewerComments = reason.trim();
    report.reviewedAt = new Date();
    report.reviewerId = req.user._id;
    report.version = (report.version || 1) + 1;
    await report.save();

    try {
      await auditService.logAudit({
        user: req.user._id,
        action: 'REJECT_REPORT',
        resource: 'Report',
        resourceId: report._id,
        details: { reason: report.reviewerComments, newVersion: report.version }
      });
    } catch (auditErr) {
      console.warn('Audit logging failed:', auditErr.message);
    }

    try {
      if (report.generatedBy) {
        notificationService.notify(
          report.generatedBy,
          `Your report "${report.title}" was rejected: ${report.reviewerComments}`,
          'warning', 'approval', report._id
        );
      }
    } catch (notifErr) {
      console.warn('Notification failed:', notifErr.message);
    }

    return sendSuccess(res, report, 'Report rejected successfully');
  } catch (error) {
    next(error);
  }
};

// 11. Evidence Details
exports.getEvidence = async (req, res, next) => {
  try {
    const evidence = await reportService.getReportEvidence(req.params.id);
    return sendSuccess(res, evidence, 'Report evidence retrieved successfully');
  } catch (error) {
    if (error.message.includes('not found')) {
      return sendError(res, error.message, 'NOT_FOUND', 404);
    }
    next(error);
  }
};

// 12. Version History
exports.getVersionHistory = async (req, res, next) => {
  try {
    const history = await reportService.getVersionHistory(req.params.id);
    return sendSuccess(res, history, 'Report version history retrieved successfully');
  } catch (error) {
    if (error.message.includes('not found')) {
      return sendError(res, error.message, 'NOT_FOUND', 404);
    }
    next(error);
  }
};

// 13. Version Changes
exports.getChanges = async (req, res, next) => {
  try {
    const changes = await reportService.getReportChanges(
      req.params.id,
      req.query.fromVersion,
      req.query.toVersion
    );
    return sendSuccess(res, changes, 'Report changes retrieved successfully');
  } catch (error) {
    if (error.message.includes('not found')) {
      return sendError(res, error.message, 'NOT_FOUND', 404);
    }
    next(error);
  }
};

// 14. Export endpoints
exports.exportPdf = async (req, res, next) => {
  try {
    const result = await reportService.exportReport(req.params.id, 'pdf');
    res.setHeader('Content-Type', result.contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${result.filename}"`);
    return res.send(result.data);
  } catch (error) {
    if (error.message.includes('not found')) {
      return sendError(res, error.message, 'NOT_FOUND', 404);
    }
    next(error);
  }
};

exports.exportDocx = async (req, res, next) => {
  try {
    const result = await reportService.exportReport(req.params.id, 'docx');
    res.setHeader('Content-Type', result.contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${result.filename}"`);
    return res.send(result.data);
  } catch (error) {
    if (error.message.includes('not found')) {
      return sendError(res, error.message, 'NOT_FOUND', 404);
    }
    next(error);
  }
};

exports.exportCsv = async (req, res, next) => {
  try {
    const result = await reportService.exportReport(req.params.id, 'csv');
    res.setHeader('Content-Type', result.contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${result.filename}"`);
    return res.send(result.data);
  } catch (error) {
    if (error.message.includes('not found')) {
      return sendError(res, error.message, 'NOT_FOUND', 404);
    }
    next(error);
  }
};

exports.exportJson = async (req, res, next) => {
  try {
    const result = await reportService.exportReport(req.params.id, 'json');
    res.setHeader('Content-Type', result.contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${result.filename}"`);
    return res.send(result.data);
  } catch (error) {
    if (error.message.includes('not found')) {
      return sendError(res, error.message, 'NOT_FOUND', 404);
    }
    next(error);
  }
};

// Legacy / query parameter export helper: GET /:id/export?format=pdf|docx|csv|json
exports.exportReport = async (req, res, next) => {
  try {
    const format = req.query.format || 'json';
    const result = await reportService.exportReport(req.params.id, format);

    res.setHeader('Content-Type', result.contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${result.filename}"`);
    return res.send(result.data);
  } catch (error) {
    if (error.message.includes('not found')) {
      return sendError(res, error.message, 'NOT_FOUND', 404);
    }
    next(error);
  }
};
