const Report = require('../models/Report');
const reportService = require('../services/reportService');
const auditService = require('../services/auditService');
const notificationService = require('../services/notificationService');

exports.getReports = async (req, res, next) => {
  try {
    const query = req.user.role === 'admin' ? {} : { generatedBy: req.user._id };
    if (req.query.status) query.status = req.query.status;
    const reports = await Report.find(query)
      .populate('generatedBy', 'username')
      .populate('reviewerId', 'username')
      .populate('approvedBy', 'username')
      .sort({ createdAt: -1 });
    res.status(200).json({ success: true, data: reports });
  } catch (error) {
    next(error);
  }
};

exports.generateReport = async (req, res, next) => {
  try {
    const { data, type } = req.body;
    if (!type) {
      return res.status(400).json({ success: false, message: 'report type is required' });
    }
    const reqContext = { userId: req.user._id, isComplex: true };
    const report = await reportService.generateReport(data || {}, type, req.user._id, reqContext);

    // Notify admins about new report
    notificationService.notifyAdmins(
      `New ${type} report generated by ${req.user.username}: "${report.title}"`,
      'info', 'report', report._id
    );

    res.status(201).json({ success: true, data: report });
  } catch (error) {
    next(error);
  }
};

exports.getReportById = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id)
      .populate('generatedBy', 'username')
      .populate('reviewerId', 'username')
      .populate('approvedBy', 'username');
    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found' });
    }
    if (req.user.role !== 'admin' && req.user.role !== 'reviewer' && report.generatedBy?._id?.toString() !== req.user._id.toString()) {
      return res.status(403).json({ success: false, message: 'Not authorized to view this report' });
    }
    res.status(200).json({ success: true, data: report });
  } catch (error) {
    next(error);
  }
};

// Submit report for review
exports.submitForReview = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });

    if (report.status !== 'draft' && report.status !== 'rejected') {
      return res.status(400).json({ success: false, message: `Cannot submit a report with status "${report.status}"` });
    }

    const { reviewerId } = req.body;
    report.status = 'review';
    if (reviewerId) report.reviewerId = reviewerId;
    await report.save();

    auditService.logAudit({
      user: req.user._id,
      action: 'SUBMIT_FOR_REVIEW',
      resource: 'Report',
      resourceId: report._id,
      details: { reviewerId }
    });

    if (reviewerId) {
      notificationService.notify(
        reviewerId,
        `Report "${report.title}" has been submitted for your review.`,
        'action', 'review', report._id
      );
    } else {
      notificationService.notifyAdmins(
        `Report "${report.title}" is awaiting review.`,
        'action', 'review', report._id
      );
    }

    res.status(200).json({ success: true, data: report });
  } catch (error) {
    next(error);
  }
};

// Approve report (admin/reviewer only)
exports.approveReport = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });

    if (report.status !== 'review') {
      return res.status(400).json({ success: false, message: 'Only reports in "review" status can be approved' });
    }

    report.status = 'approved';
    report.approvedBy = req.user._id;
    report.approvedAt = new Date();
    report.reviewerComments = req.body.comments || '';
    report.reviewedAt = new Date();
    await report.save();

    auditService.logAudit({
      user: req.user._id,
      action: 'APPROVE_REPORT',
      resource: 'Report',
      resourceId: report._id,
      details: { comments: req.body.comments }
    });

    if (report.generatedBy) {
      notificationService.notify(
        report.generatedBy,
        `Your report "${report.title}" has been approved.`,
        'success', 'approval', report._id
      );
    }

    res.status(200).json({ success: true, data: report });
  } catch (error) {
    next(error);
  }
};

// Reject report (admin/reviewer only)
exports.rejectReport = async (req, res, next) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });

    if (report.status !== 'review') {
      return res.status(400).json({ success: false, message: 'Only reports in "review" status can be rejected' });
    }

    // Save current version before rejecting
    report.previousVersions.push({
      content: report.content,
      version: report.version,
      date: new Date()
    });

    report.status = 'rejected';
    report.reviewerComments = req.body.comments || 'No comments provided';
    report.reviewedAt = new Date();
    report.version += 1;
    await report.save();

    auditService.logAudit({
      user: req.user._id,
      action: 'REJECT_REPORT',
      resource: 'Report',
      resourceId: report._id,
      details: { comments: req.body.comments }
    });

    if (report.generatedBy) {
      notificationService.notify(
        report.generatedBy,
        `Your report "${report.title}" was rejected: ${req.body.comments || 'See reviewer comments'}`,
        'warning', 'approval', report._id
      );
    }

    res.status(200).json({ success: true, data: report });
  } catch (error) {
    next(error);
  }
};

// Export report in various formats
exports.exportReport = async (req, res, next) => {
  try {
    const format = req.query.format || 'json';
    const result = await reportService.exportReport(req.params.id, format);

    res.setHeader('Content-Type', result.contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${result.filename}"`);
    res.send(result.data);
  } catch (error) {
    next(error);
  }
};
